analyzer:
  exclude:
    - "lib/bip39/**.*dart" # There's good reason to ignore this, and I'm trying to keep it as close to the source code I copied from as possible for later merging/updating.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    avoid_print: false
