name: scan
description: A Flutter QR/barcode scanner widget with camera view and image parsing.
version: 0.0.1
homepage: https://github.com/gearscrafter/scan
repository: https://github.com/gearscrafter/scan
issue_tracker: https://github.com/gearscrafter/scan/issues
topics:
  - qr
  - barcode
  - scanner
  - camera
  - image

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gearscrafter.scan
        pluginClass: ScanPlugin
      ios:
        pluginClass: ScanPlugin

license: MIT
